In [2]:
import pandas as pd
import os
import glob
import geopandas as gpd

In [3]:
filename_list_example = pd.read_csv("parameter_files/new_filenames_on_pause/wales_filenames_00.csv", header=None, names=["filename"])

old_filename_list = pd.read_csv("wales_filenames.csv")

In [4]:
old_filename_list

                                 filename
0             Swansea_pp_or_g_cmb.geojson
1   Rhondda Cynon Taf_pp_or_g_cmb.geojson
2        Denbighshire_pp_or_g_cmb.geojson
3             Torfaen_pp_or_g_cmb.geojson
4   Vale of Glamorgan_pp_or_g_cmb.geojson
5               Powys_pp_or_g_cmb.geojson
6     Carmarthenshire_pp_or_g_cmb.geojson
7            Bridgend_pp_or_g_cmb.geojson
8       Blaenau Gwent_pp_or_g_cmb.geojson
9             Cardiff_pp_or_g_cmb.geojson
10         Ceredigion_pp_or_g_cmb.geojson
11              Conwy_pp_or_g_cmb.geojson
12      Pembrokeshire_pp_or_g_cmb.geojson
13         Flintshire_pp_or_g_cmb.geojson
14     Merthyr Tydfil_pp_or_g_cmb.geojson
15            Newport_pp_or_g_cmb.geojson
16            Gwynedd_pp_or_g_cmb.geojson
17  Neath Port Talbot_pp_or_g_cmb.geojson
18            Wrexham_pp_or_g_cmb.geojson
19         Caerphilly_pp_or_g_cmb.geojson
20      Monmouthshire_pp_or_g_cmb.geojson
21   Isle of Anglesey_pp_or_g_cmb.geojson

In [5]:
filename_list_example

                           filename
0               Conwy_parks.geojson
1          Flintshire_parks.geojson
2       Blaenau Gwent_parks.geojson
3            Bridgend_parks.geojson
4               Powys_parks.geojson
5     Carmarthenshire_parks.geojson
6   Vale of Glamorgan_parks.geojson
7      Merthyr Tydfil_parks.geojson
8   Neath Port Talbot_parks.geojson
9          Ceredigion_parks.geojson
10            Newport_parks.geojson
11      Pembrokeshire_parks.geojson
12            Torfaen_parks.geojson
13            Wrexham_parks.geojson
14   Isle of Anglesey_parks.geojson
15            Cardiff_parks.geojson
16            Swansea_parks.geojson
17         Caerphilly_parks.geojson
18  Rhondda Cynon Taf_parks.geojson
19      Monmouthshire_parks.geojson
20            Gwynedd_parks.geojson

In [6]:
filename_list_example["old_name"] = filename_list_example["filename"].apply(lambda x: x.replace("_parks.geojson", "_pp_or_g_cmb.geojson"))

In [7]:
# now join the dataframes to check if they match up
merged_df = filename_list_example.merge(old_filename_list, left_on="old_name", right_on="filename", how="left", indicator=True)

In [8]:
merged_df

,filename_x,old_name,filename_y,_merge
0,Conwy_parks.geojson,Conwy_pp_or_g_cmb.geojson,Conwy_pp_or_g_cmb.geojson,both
1,Flintshire_parks.geojson,Flintshire_pp_or_g_cmb.geojson,Flintshire_pp_or_g_cmb.geojson,both
2,Blaenau Gwent_parks.geojson,Blaenau Gwent_pp_or_g_cmb.geojson,Blaenau Gwent_pp_or_g_cmb.geojson,both
3,Bridgend_parks.geojson,Bridgend_pp_or_g_cmb.geojson,Bridgend_pp_or_g_cmb.geojson,both
4,Powys_parks.geojson,Powys_pp_or_g_cmb.geojson,Powys_pp_or_g_cmb.geojson,both
5,Carmarthenshire_parks.geojson,Carmarthenshire_pp_or_g_cmb.geojson,Carmarthenshire_pp_or_g_cmb.geojson,both
6,Vale of Glamorgan_parks.geojson,Vale of Glamorgan_pp_or_g_cmb.geojson,Vale of Glamorgan_pp_or_g_cmb.geojson,both
7,Merthyr Tydfil_parks.geojson,Merthyr Tydfil_pp_or_g_cmb.geojson,Merthyr Tydfil_pp_or_g_cmb.geojson,both
8,Neath Port Talbot_parks.geojson,Neath Port Talbot_pp_or_g_cmb.geojson,Neath Port Talbot_pp_or_g_cmb.geojson,both
9,Ceredigion_parks.geojson,Ceredigion_pp_or_g_cmb.geojson,Ceredigion_pp_or_g_cmb.geojson,both
10,Newport_parks.geojson,Newport_pp_or_g_cmb.geojson,Newport_pp_or_g_cmb.geojson,both
11,Pembrokeshire_parks.geojson,Pembrokeshire_pp_or_g_cmb.geojson,Pembrokeshire_pp_or_g_cmb.geojson,both
12,Torfaen_parks.geojson,Torfaen_pp_or_g_cmb.geojson,Torfaen_pp_or_g_cmb.geojson,both
13,Wrexham_parks.geojson,Wrexham_pp_or_g_cmb.geojson,Wrexham_pp_or_g_cmb.geojson,both
14,Isle of Anglesey_parks.geojson,Isle of Anglesey_pp_or_g_cmb.geojson,Isle of Anglesey_pp_or_g_cmb.geojson,both
15,Cardiff_parks.geojson,Cardiff_pp_or_g_cmb.geojson,Cardiff_pp_or_g_cmb.geojson,both
16,Swansea_parks.geojson,Swansea_pp_or_g_cmb.geojson,Swansea_pp_or_g_cmb.geojson,both
17,Caerphilly_parks.geojson,Caerphilly_pp_or_g_cmb.geojson,Caerphilly_pp_or_g_cmb.geojson,both
18,Rhondda Cynon Taf_parks.geojson,Rhondda Cynon Taf_pp_or_g_cmb.geojson,Rhondda Cynon Taf_pp_or_g_cmb.geojson,both
19,Monmouthshire_parks.geojson,Monmouthshire_pp_or_g_cmb.geojson,Monmouthshire_pp_or_g_cmb.geojson,both
20,Gwynedd_parks.geojson,Gwynedd_pp_or_g_cmb.geojson,Gwynedd_pp_or_g_cmb.geojson,both

In [9]:
# find and list any parks/gardens that are in the old list but not in the new list
missing_in_new_list = old_filename_list[~old_filename_list["filename"].isin(merged_df["old_name"])]

In [10]:
missing_in_new_list

                           filename
2  Denbighshire_pp_or_g_cmb.geojson

Missing areas:

Denbighshire_pp_or_g_cmb.geojson

In [11]:
# convert the LUT file filenames to new version

lut_file = "../example_datasets/LUT_regions_authorities_filenames.geojson"

check_regions_gdf = gpd.read_file(lut_file)

In [12]:
check_regions_gdf

,region_id,reg_name_e,reg_name_w,authority_id,auth_name_e,auth_name_w,country,filename,placename,region,geometry
0,W10000009,South Wales West,Gorllewin De Cymru,W06000011,Swansea,Abertawe,Wales,Swansea_pp_or_g_cmb.geojson,Swansea,W10000009,None
1,W10000007,South Wales Central,Canol De Cymru,W06000016,Rhondda Cynon Taf,Rhondda Cynon Taf,Wales,Rhondda Cynon Taf_pp_or_g_cmb.geojson,Rhondda Cynon Taf,W10000007,None
2,W10000001,North Wales,Gogledd Cymru,W06000004,Denbighshire,Sir Ddinbych,Wales,Denbighshire_pp_or_g_cmb.geojson,Denbighshire,W10000001,None
3,W10000008,South Wales East,Dwyrain De Cymru,W06000020,Torfaen,Tor-faen,Wales,Torfaen_pp_or_g_cmb.geojson,Torfaen,W10000008,None
4,W10000007,South Wales Central,Canol De Cymru,W06000014,Vale of Glamorgan,Bro Morgannwg,Wales,Vale of Glamorgan_pp_or_g_cmb.geojson,Vale of Glamorgan,W10000007,None
...,...,...,...,...,...,...,...,...,...,...,...
313,E12000002,North West,NaN,E08000009,Trafford,NaN,England,Trafford_pp_or_g_cmb.geojson,Trafford,E12000002,None
314,E12000002,North West,NaN,E08000010,Wigan,NaN,England,Wigan_pp_or_g_cmb.geojson,Wigan,E12000002,None
315,E12000002,North West,NaN,E08000011,Knowsley,NaN,England,Knowsley_pp_or_g_cmb.geojson,Knowsley,E12000002,None
316,E12000002,North West,NaN,E08000012,Liverpool,NaN,England,Liverpool_pp_or_g_cmb.geojson,Liverpool,E12000002,None
317,E12000002,North West,NaN,E08000013,St. Helens,NaN,England,St. Helens_pp_or_g_cmb.geojson,St. Helens,E12000002,None

In [13]:
check_regions_gdf["old_filename"] = check_regions_gdf["filename"]
check_regions_gdf["filename"] = check_regions_gdf["filename"].apply(lambda x: x.replace("_pp_or_g_cmb.geojson", "_parks.geojson"))

In [14]:
check_regions_gdf

,region_id,reg_name_e,reg_name_w,authority_id,auth_name_e,auth_name_w,country,filename,placename,region,geometry,old_filename
0,W10000009,South Wales West,Gorllewin De Cymru,W06000011,Swansea,Abertawe,Wales,Swansea_parks.geojson,Swansea,W10000009,None,Swansea_pp_or_g_cmb.geojson
1,W10000007,South Wales Central,Canol De Cymru,W06000016,Rhondda Cynon Taf,Rhondda Cynon Taf,Wales,Rhondda Cynon Taf_parks.geojson,Rhondda Cynon Taf,W10000007,None,Rhondda Cynon Taf_pp_or_g_cmb.geojson
2,W10000001,North Wales,Gogledd Cymru,W06000004,Denbighshire,Sir Ddinbych,Wales,Denbighshire_parks.geojson,Denbighshire,W10000001,None,Denbighshire_pp_or_g_cmb.geojson
3,W10000008,South Wales East,Dwyrain De Cymru,W06000020,Torfaen,Tor-faen,Wales,Torfaen_parks.geojson,Torfaen,W10000008,None,Torfaen_pp_or_g_cmb.geojson
4,W10000007,South Wales Central,Canol De Cymru,W06000014,Vale of Glamorgan,Bro Morgannwg,Wales,Vale of Glamorgan_parks.geojson,Vale of Glamorgan,W10000007,None,Vale of Glamorgan_pp_or_g_cmb.geojson
...,...,...,...,...,...,...,...,...,...,...,...,...
313,E12000002,North West,NaN,E08000009,Trafford,NaN,England,Trafford_parks.geojson,Trafford,E12000002,None,Trafford_pp_or_g_cmb.geojson
314,E12000002,North West,NaN,E08000010,Wigan,NaN,England,Wigan_parks.geojson,Wigan,E12000002,None,Wigan_pp_or_g_cmb.geojson
315,E12000002,North West,NaN,E08000011,Knowsley,NaN,England,Knowsley_parks.geojson,Knowsley,E12000002,None,Knowsley_pp_or_g_cmb.geojson
316,E12000002,North West,NaN,E08000012,Liverpool,NaN,England,Liverpool_parks.geojson,Liverpool,E12000002,None,Liverpool_pp_or_g_cmb.geojson
317,E12000002,North West,NaN,E08000013,St. Helens,NaN,England,St. Helens_parks.geojson,St. Helens,E12000002,None,St. Helens_pp_or_g_cmb.geojson

In [15]:
# in the filename column and old filename column, replace any St. with St to prevent filename issues

check_regions_gdf["filename"] = check_regions_gdf["filename"].str.replace("St.", "St", regex=False)

In [16]:
check_regions_gdf

,region_id,reg_name_e,reg_name_w,authority_id,auth_name_e,auth_name_w,country,filename,placename,region,geometry,old_filename
0,W10000009,South Wales West,Gorllewin De Cymru,W06000011,Swansea,Abertawe,Wales,Swansea_parks.geojson,Swansea,W10000009,None,Swansea_pp_or_g_cmb.geojson
1,W10000007,South Wales Central,Canol De Cymru,W06000016,Rhondda Cynon Taf,Rhondda Cynon Taf,Wales,Rhondda Cynon Taf_parks.geojson,Rhondda Cynon Taf,W10000007,None,Rhondda Cynon Taf_pp_or_g_cmb.geojson
2,W10000001,North Wales,Gogledd Cymru,W06000004,Denbighshire,Sir Ddinbych,Wales,Denbighshire_parks.geojson,Denbighshire,W10000001,None,Denbighshire_pp_or_g_cmb.geojson
3,W10000008,South Wales East,Dwyrain De Cymru,W06000020,Torfaen,Tor-faen,Wales,Torfaen_parks.geojson,Torfaen,W10000008,None,Torfaen_pp_or_g_cmb.geojson
4,W10000007,South Wales Central,Canol De Cymru,W06000014,Vale of Glamorgan,Bro Morgannwg,Wales,Vale of Glamorgan_parks.geojson,Vale of Glamorgan,W10000007,None,Vale of Glamorgan_pp_or_g_cmb.geojson
...,...,...,...,...,...,...,...,...,...,...,...,...
313,E12000002,North West,NaN,E08000009,Trafford,NaN,England,Trafford_parks.geojson,Trafford,E12000002,None,Trafford_pp_or_g_cmb.geojson
314,E12000002,North West,NaN,E08000010,Wigan,NaN,England,Wigan_parks.geojson,Wigan,E12000002,None,Wigan_pp_or_g_cmb.geojson
315,E12000002,North West,NaN,E08000011,Knowsley,NaN,England,Knowsley_parks.geojson,Knowsley,E12000002,None,Knowsley_pp_or_g_cmb.geojson
316,E12000002,North West,NaN,E08000012,Liverpool,NaN,England,Liverpool_parks.geojson,Liverpool,E12000002,None,Liverpool_pp_or_g_cmb.geojson
317,E12000002,North West,NaN,E08000013,St. Helens,NaN,England,St Helens_parks.geojson,St. Helens,E12000002,None,St. Helens_pp_or_g_cmb.geojson

In [17]:
folders = glob.glob("parks_final/*")
folders = [f for f in folders if "pocket_parks" not in f]
folders = [f.replace("parks_final/", "") for f in folders]
folder_df = pd.DataFrame(folders, columns=["folder_name"])

In [18]:
folder_df

                                   folder_name
0    Kingston upon Hull, City of_parks.geojson
1                       Cornwall_parks.geojson
2            Newcastle upon Tyne_parks.geojson
3                         Rother_parks.geojson
4                       Rochford_parks.geojson
..                                         ...
291                      Gwynedd_parks.geojson
292                    Worcester_parks.geojson
293             Stockton-on-Tees_parks.geojson
294          Vale of White Horse_parks.geojson
295                    Mid Devon_parks.geojson

[296 rows x 1 columns]

In [19]:
# make a list of any parks in check_regions_gdf.filename but not in the folder_df.folder_name

missing_in_new_list = check_regions_gdf[~check_regions_gdf["filename"].isin(folder_df["folder_name"])]

In [20]:
missing_in_new_list

,region_id,reg_name_e,reg_name_w,authority_id,auth_name_e,auth_name_w,country,filename,placename,region,geometry,old_filename
2,W10000001,North Wales,Gogledd Cymru,W06000004,Denbighshire,Sir Ddinbych,Wales,Denbighshire_parks.geojson,Denbighshire,W10000001,None,Denbighshire_pp_or_g_cmb.geojson
32,E12000003,Yorkshire and The Humber,NaN,E06000011,East Riding of Yorkshire,NaN,England,East Riding of Yorkshire_parks.geojson,East Riding of Yorkshire,E12000003,None,East Riding of Yorkshire_pp_or_g_cmb.geojson
34,E12000003,Yorkshire and The Humber,NaN,E06000013,North Lincolnshire,NaN,England,North Lincolnshire_parks.geojson,North Lincolnshire,E12000003,None,North Lincolnshire_pp_or_g_cmb.geojson
35,E12000003,Yorkshire and The Humber,NaN,E06000014,York,NaN,England,York_parks.geojson,York,E12000003,None,York_pp_or_g_cmb.geojson
53,E12000006,East of England,NaN,E06000034,Thurrock,NaN,England,Thurrock_parks.geojson,Thurrock,E12000006,None,Thurrock_pp_or_g_cmb.geojson
54,E12000008,South East,NaN,E06000035,Medway,NaN,England,Medway_parks.geojson,Medway,E12000008,None,Medway_pp_or_g_cmb.geojson
67,E12000002,North West,NaN,E06000049,Cheshire East,NaN,England,Cheshire East_parks.geojson,Cheshire East,E12000002,None,Cheshire East_pp_or_g_cmb.geojson
78,E12000008,South East,NaN,E06000060,Buckinghamshire,NaN,England,Buckinghamshire_parks.geojson,Buckinghamshire,E12000008,None,Buckinghamshire_pp_or_g_cmb.geojson
80,E12000004,East Midlands,NaN,E06000062,West Northamptonshire,NaN,England,West Northamptonshire_parks.geojson,West Northamptonshire,E12000004,None,West Northamptonshire_pp_or_g_cmb.geojson
83,E12000003,Yorkshire and The Humber,NaN,E06000065,North Yorkshire,NaN,England,North Yorkshire_parks.geojson,North Yorkshire,E12000003,None,North Yorkshire_pp_or_g_cmb.geojson
182,E12000004,East Midlands,NaN,E07000141,South Kesteven,NaN,England,South Kesteven_parks.geojson,South Kesteven,E12000004,None,South Kesteven_pp_or_g_cmb.geojson
212,E12000005,West Midlands,NaN,E08000025,Birmingham,NaN,England,Birmingham_parks.geojson,Birmingham,E12000005,None,Birmingham_pp_or_g_cmb.geojson
215,E12000005,West Midlands,NaN,E08000028,Sandwell,NaN,England,Sandwell_parks.geojson,Sandwell,E12000005,None,Sandwell_pp_or_g_cmb.geojson
217,E12000005,West Midlands,NaN,E08000030,Walsall,NaN,England,Walsall_parks.geojson,Walsall,E12000005,None,Walsall_pp_or_g_cmb.geojson
251,E12000007,London,NaN,E09000027,Richmond upon Thames,NaN,England,Richmond upon Thames_parks.geojson,Richmond upon Thames,E12000007,None,Richmond upon Thames_pp_or_g_cmb.geojson
273,E12000008,South East,NaN,E07000210,Mole Valley,NaN,England,Mole Valley_parks.geojson,Mole Valley,E12000008,None,Mole Valley_pp_or_g_cmb.geojson
290,E12000008,South East,NaN,E07000227,Horsham,NaN,England,Horsham_parks.geojson,Horsham,E12000008,None,Horsham_pp_or_g_cmb.geojson
307,E12000002,North West,NaN,E08000003,Manchester,NaN,England,Manchester_parks.geojson,Manchester,E12000002,None,Manchester_pp_or_g_cmb.geojson
308,E12000002,North West,NaN,E08000004,Oldham,NaN,England,Oldham_parks.geojson,Oldham,E12000002,None,Oldham_pp_or_g_cmb.geojson
310,E12000002,North West,NaN,E08000006,Salford,NaN,England,Salford_parks.geojson,Salford,E12000002,None,Salford_pp_or_g_cmb.geojson
311,E12000002,North West,NaN,E08000007,Stockport,NaN,England,Stockport_parks.geojson,Stockport,E12000002,None,Stockport_pp_or_g_cmb.geojson
315,E12000002,North West,NaN,E08000011,Knowsley,NaN,England,Knowsley_parks.geojson,Knowsley,E12000002,None,Knowsley_pp_or_g_cmb.geojson

In [21]:
# missing_in_new_list.to_csv("missing_large_parks_in_new_data.csv", index=False)

In [22]:
folders = glob.glob("parks_final/*")
# folders = [f for f in folders if "pocket_parks" in f]
folders = [f.replace("parks_final/", "") for f in folders]
folder_df = pd.DataFrame(folders, columns=["folder_name"])

In [23]:
folder_df["folder_name"] = folder_df["folder_name"].str.replace("pocket_", "", regex=False)
folder_df

                                   folder_name
0    Kingston upon Hull, City of_parks.geojson
1                       Cornwall_parks.geojson
2          Blackburn with Darwen_parks.geojson
3                         Havant_parks.geojson
4            Newcastle upon Tyne_parks.geojson
..                                         ...
587                    Mid Devon_parks.geojson
588                  Teignbridge_parks.geojson
589                 Three Rivers_parks.geojson
590                       Bexley_parks.geojson
591                       Woking_parks.geojson

[592 rows x 1 columns]

In [24]:
# remove duplicate rows in the folder_df dataframe

folder_df = folder_df.drop_duplicates(subset=["folder_name"])

folder_df

                                   folder_name
0    Kingston upon Hull, City of_parks.geojson
1                       Cornwall_parks.geojson
2          Blackburn with Darwen_parks.geojson
3                         Havant_parks.geojson
4            Newcastle upon Tyne_parks.geojson
..                                         ...
522                    Elmbridge_parks.geojson
543         South Cambridgeshire_parks.geojson
565                Wolverhampton_parks.geojson
569                       Bexley_parks.geojson
580                      Gwynedd_parks.geojson

[296 rows x 1 columns]

In [25]:
# make a list of any parks in check_regions_gdf.filename but not in the folder_df.folder_name

missing_in_new_list = check_regions_gdf[~check_regions_gdf["filename"].isin(folder_df["folder_name"])]

In [26]:
missing_in_new_list

,region_id,reg_name_e,reg_name_w,authority_id,auth_name_e,auth_name_w,country,filename,placename,region,geometry,old_filename
2,W10000001,North Wales,Gogledd Cymru,W06000004,Denbighshire,Sir Ddinbych,Wales,Denbighshire_parks.geojson,Denbighshire,W10000001,None,Denbighshire_pp_or_g_cmb.geojson
32,E12000003,Yorkshire and The Humber,NaN,E06000011,East Riding of Yorkshire,NaN,England,East Riding of Yorkshire_parks.geojson,East Riding of Yorkshire,E12000003,None,East Riding of Yorkshire_pp_or_g_cmb.geojson
34,E12000003,Yorkshire and The Humber,NaN,E06000013,North Lincolnshire,NaN,England,North Lincolnshire_parks.geojson,North Lincolnshire,E12000003,None,North Lincolnshire_pp_or_g_cmb.geojson
35,E12000003,Yorkshire and The Humber,NaN,E06000014,York,NaN,England,York_parks.geojson,York,E12000003,None,York_pp_or_g_cmb.geojson
53,E12000006,East of England,NaN,E06000034,Thurrock,NaN,England,Thurrock_parks.geojson,Thurrock,E12000006,None,Thurrock_pp_or_g_cmb.geojson
54,E12000008,South East,NaN,E06000035,Medway,NaN,England,Medway_parks.geojson,Medway,E12000008,None,Medway_pp_or_g_cmb.geojson
67,E12000002,North West,NaN,E06000049,Cheshire East,NaN,England,Cheshire East_parks.geojson,Cheshire East,E12000002,None,Cheshire East_pp_or_g_cmb.geojson
78,E12000008,South East,NaN,E06000060,Buckinghamshire,NaN,England,Buckinghamshire_parks.geojson,Buckinghamshire,E12000008,None,Buckinghamshire_pp_or_g_cmb.geojson
80,E12000004,East Midlands,NaN,E06000062,West Northamptonshire,NaN,England,West Northamptonshire_parks.geojson,West Northamptonshire,E12000004,None,West Northamptonshire_pp_or_g_cmb.geojson
83,E12000003,Yorkshire and The Humber,NaN,E06000065,North Yorkshire,NaN,England,North Yorkshire_parks.geojson,North Yorkshire,E12000003,None,North Yorkshire_pp_or_g_cmb.geojson
182,E12000004,East Midlands,NaN,E07000141,South Kesteven,NaN,England,South Kesteven_parks.geojson,South Kesteven,E12000004,None,South Kesteven_pp_or_g_cmb.geojson
212,E12000005,West Midlands,NaN,E08000025,Birmingham,NaN,England,Birmingham_parks.geojson,Birmingham,E12000005,None,Birmingham_pp_or_g_cmb.geojson
215,E12000005,West Midlands,NaN,E08000028,Sandwell,NaN,England,Sandwell_parks.geojson,Sandwell,E12000005,None,Sandwell_pp_or_g_cmb.geojson
217,E12000005,West Midlands,NaN,E08000030,Walsall,NaN,England,Walsall_parks.geojson,Walsall,E12000005,None,Walsall_pp_or_g_cmb.geojson
251,E12000007,London,NaN,E09000027,Richmond upon Thames,NaN,England,Richmond upon Thames_parks.geojson,Richmond upon Thames,E12000007,None,Richmond upon Thames_pp_or_g_cmb.geojson
273,E12000008,South East,NaN,E07000210,Mole Valley,NaN,England,Mole Valley_parks.geojson,Mole Valley,E12000008,None,Mole Valley_pp_or_g_cmb.geojson
290,E12000008,South East,NaN,E07000227,Horsham,NaN,England,Horsham_parks.geojson,Horsham,E12000008,None,Horsham_pp_or_g_cmb.geojson
307,E12000002,North West,NaN,E08000003,Manchester,NaN,England,Manchester_parks.geojson,Manchester,E12000002,None,Manchester_pp_or_g_cmb.geojson
308,E12000002,North West,NaN,E08000004,Oldham,NaN,England,Oldham_parks.geojson,Oldham,E12000002,None,Oldham_pp_or_g_cmb.geojson
310,E12000002,North West,NaN,E08000006,Salford,NaN,England,Salford_parks.geojson,Salford,E12000002,None,Salford_pp_or_g_cmb.geojson
311,E12000002,North West,NaN,E08000007,Stockport,NaN,England,Stockport_parks.geojson,Stockport,E12000002,None,Stockport_pp_or_g_cmb.geojson
315,E12000002,North West,NaN,E08000011,Knowsley,NaN,England,Knowsley_parks.geojson,Knowsley,E12000002,None,Knowsley_pp_or_g_cmb.geojson

In [27]:
# missing_in_new_list.to_csv("missing_large_or_pocket_parks_in_new_data.csv", index=False)

In [31]:
# ok, now I want to check if there are new files that aren't in the old list

folders = glob.glob("parks_final/*")
# folders = [f for f in folders if "pocket_parks" in f]
folders = [f.replace("parks_final/", "") for f in folders]
folder_df = pd.DataFrame(folders, columns=["folder_name"])
folder_df["folder_name"] = folder_df["folder_name"].str.replace("pocket_", "", regex=False)
folder_df = folder_df.drop_duplicates(subset=["folder_name"])

folder_df

                                   folder_name
0    Kingston upon Hull, City of_parks.geojson
1                       Cornwall_parks.geojson
2          Blackburn with Darwen_parks.geojson
3                         Havant_parks.geojson
4            Newcastle upon Tyne_parks.geojson
..                                         ...
522                    Elmbridge_parks.geojson
543         South Cambridgeshire_parks.geojson
565                Wolverhampton_parks.geojson
569                       Bexley_parks.geojson
580                      Gwynedd_parks.geojson

[296 rows x 1 columns]

In [32]:
# missing_in_new_list = check_regions_gdf[~check_regions_gdf["filename"].isin(folder_df["folder_name"])]

missing_in_old_list = folder_df[~folder_df["folder_name"].isin(check_regions_gdf["filename"])]

In [33]:
missing_in_old_list

Empty DataFrame
Columns: [folder_name]
Index: []