See how many areas/parks have been completed

In [414]:
import pandas as pd
import geopandas as gpd
import os

In [415]:
output_dir = "../workflow_outputs/"
filenames_file = "england_filenames.csv"
park_id_file = "all_parks_ids.csv"

In [416]:
filenames = pd.read_csv(filenames_file)
park_ids = pd.read_csv(park_id_file)

In [417]:
# want a subset of the parks that are in process, so we can check the progress of the workflow
# first_park_index = 29
# last_park_index = first_park_index + 30
# filenames= filenames.iloc[first_park_index:last_park_index]

In [418]:
filenames

                                     filename
0              Hartlepool_pp_or_g_cmb.geojson
1           Middlesbrough_pp_or_g_cmb.geojson
2    Redcar and Cleveland_pp_or_g_cmb.geojson
3        Stockton-on-Tees_pp_or_g_cmb.geojson
4              Darlington_pp_or_g_cmb.geojson
..                                        ...
291              Trafford_pp_or_g_cmb.geojson
292                 Wigan_pp_or_g_cmb.geojson
293              Knowsley_pp_or_g_cmb.geojson
294             Liverpool_pp_or_g_cmb.geojson
295            St. Helens_pp_or_g_cmb.geojson

[296 rows x 1 columns]

In [419]:
# for each filename in filenames
# get foldername by removing the .geojson
# check if the folder exists in output_dir
# add existing folder to a list

in_process_areas = []
for filename in filenames["filename"]:
    foldername = filename.replace(".geojson", "")
    folderpath = output_dir + foldername
    if os.path.exists(folderpath):
        in_process_areas.append(foldername)

In [420]:
100*len(in_process_areas)/len(filenames)

19.93243243243243

In [421]:
in_process_area_names = []
for filename in in_process_areas:
    areaname = filename.replace("_pp_or_g_cmb", "")
    in_process_area_names.append(areaname)

In [422]:
area_df = pd.DataFrame({"area_name": in_process_area_names,
                        "filename": in_process_areas,
                        "folder_path": [output_dir + filename for filename in in_process_areas]})

In [423]:
park_ids

,country,region_id,authority_id,auth_name_e,old_park_id,new_park_id
0,Wales,W10000009,W06000011,Swansea,SWANS_841e2e988f55;SWANS_9add957b9b60,3816d9f14391
1,Wales,W10000009,W06000011,Swansea,SWANS_64180ad89ee2;SWANS_7875d4152bbb,eeb8a45abba6
2,Wales,W10000009,W06000011,Swansea,SWANS_0077e0499336;SWANS_003142c8af8d,2afa4425d6cc
3,Wales,W10000009,W06000011,Swansea,SWANS_8c5a5b68c7e1;SWANS_fb7bfbb4dae0,ee93e1ee473b
4,Wales,W10000009,W06000011,Swansea,SWANS_8119996c470b,a7f47d7bf887
...,...,...,...,...,...,...
217614,England,E12000002,E08000013,St. Helens,STHEL_6a530cb0f057,e97074068e56
217615,England,E12000002,E08000013,St. Helens,STHEL_2df5277ef0c9,f9627d5e096b
217616,England,E12000002,E08000013,St. Helens,STHEL_04f0db6f2403,7957ab4ecde8
217617,England,E12000002,E08000013,St. Helens,STHEL_0384f41414f0,42c0619d2802
217618,England,E12000002,E08000013,St. Helens,STHEL_009113ae693d,bceefa00da6a

In [424]:
area_df

,area_name,filename,folder_path
0,Hartlepool,Hartlepool_pp_or_g_cmb,../workflow_outputs/Hartlepool_pp_or_g_cmb
1,Middlesbrough,Middlesbrough_pp_or_g_cmb,../workflow_outputs/Middlesbrough_pp_or_g_cmb
2,Redcar and Cleveland,Redcar and Cleveland_pp_or_g_cmb,../workflow_outputs/Redcar and Cleveland_pp_or...
3,Stockton-on-Tees,Stockton-on-Tees_pp_or_g_cmb,../workflow_outputs/Stockton-on-Tees_pp_or_g_cmb
4,Darlington,Darlington_pp_or_g_cmb,../workflow_outputs/Darlington_pp_or_g_cmb
5,Halton,Halton_pp_or_g_cmb,../workflow_outputs/Halton_pp_or_g_cmb
6,Warrington,Warrington_pp_or_g_cmb,../workflow_outputs/Warrington_pp_or_g_cmb
7,Blackburn with Darwen,Blackburn with Darwen_pp_or_g_cmb,../workflow_outputs/Blackburn with Darwen_pp_o...
8,Blackpool,Blackpool_pp_or_g_cmb,../workflow_outputs/Blackpool_pp_or_g_cmb
9,"Kingston upon Hull, City of","Kingston upon Hull, City of_pp_or_g_cmb","../workflow_outputs/Kingston upon Hull, City o..."
10,East Riding of Yorkshire,East Riding of Yorkshire_pp_or_g_cmb,../workflow_outputs/East Riding of Yorkshire_p...
11,North East Lincolnshire,North East Lincolnshire_pp_or_g_cmb,../workflow_outputs/North East Lincolnshire_pp...
12,North Lincolnshire,North Lincolnshire_pp_or_g_cmb,../workflow_outputs/North Lincolnshire_pp_or_g...
13,York,York_pp_or_g_cmb,../workflow_outputs/York_pp_or_g_cmb
14,Derby,Derby_pp_or_g_cmb,../workflow_outputs/Derby_pp_or_g_cmb
15,Leicester,Leicester_pp_or_g_cmb,../workflow_outputs/Leicester_pp_or_g_cmb
16,Rutland,Rutland_pp_or_g_cmb,../workflow_outputs/Rutland_pp_or_g_cmb
17,Nottingham,Nottingham_pp_or_g_cmb,../workflow_outputs/Nottingham_pp_or_g_cmb
18,"Herefordshire, County of","Herefordshire, County of_pp_or_g_cmb","../workflow_outputs/Herefordshire, County of_p..."
19,Telford and Wrekin,Telford and Wrekin_pp_or_g_cmb,../workflow_outputs/Telford and Wrekin_pp_or_g...
20,Stoke-on-Trent,Stoke-on-Trent_pp_or_g_cmb,../workflow_outputs/Stoke-on-Trent_pp_or_g_cmb
21,Bath and North East Somerset,Bath and North East Somerset_pp_or_g_cmb,../workflow_outputs/Bath and North East Somers...
22,"Bristol, City of","Bristol, City of_pp_or_g_cmb","../workflow_outputs/Bristol, City of_pp_or_g_cmb"
23,North Somerset,North Somerset_pp_or_g_cmb,../workflow_outputs/North Somerset_pp_or_g_cmb
24,South Gloucestershire,South Gloucestershire_pp_or_g_cmb,../workflow_outputs/South Gloucestershire_pp_o...
25,Plymouth,Plymouth_pp_or_g_cmb,../workflow_outputs/Plymouth_pp_or_g_cmb
26,Torbay,Torbay_pp_or_g_cmb,../workflow_outputs/Torbay_pp_or_g_cmb
27,Swindon,Swindon_pp_or_g_cmb,../workflow_outputs/Swindon_pp_or_g_cmb
28,Peterborough,Peterborough_pp_or_g_cmb,../workflow_outputs/Peterborough_pp_or_g_cmb
29,Luton,Luton_pp_or_g_cmb,../workflow_outputs/Luton_pp_or_g_cmb
30,Southend-on-Sea,Southend-on-Sea_pp_or_g_cmb,../workflow_outputs/Southend-on-Sea_pp_or_g_cmb
31,Thurrock,Thurrock_pp_or_g_cmb,../workflow_outputs/Thurrock_pp_or_g_cmb
32,Medway,Medway_pp_or_g_cmb,../workflow_outputs/Medway_pp_or_g_cmb
33,Bracknell Forest,Bracknell Forest_pp_or_g_cmb,../workflow_outputs/Bracknell Forest_pp_or_g_cmb
34,West Berkshire,West Berkshire_pp_or_g_cmb,../workflow_outputs/West Berkshire_pp_or_g_cmb
35,Reading,Reading_pp_or_g_cmb,../workflow_outputs/Reading_pp_or_g_cmb
36,Slough,Slough_pp_or_g_cmb,../workflow_outputs/Slough_pp_or_g_cmb
37,Windsor and Maidenhead,Windsor and Maidenhead_pp_or_g_cmb,../workflow_outputs/Windsor and Maidenhead_pp_...
38,Wokingham,Wokingham_pp_or_g_cmb,../workflow_outputs/Wokingham_pp_or_g_cmb
39,Milton Keynes,Milton Keynes_pp_or_g_cmb,../workflow_outputs/Milton Keynes_pp_or_g_cmb
40,Brighton and Hove,Brighton and Hove_pp_or_g_cmb,../workflow_outputs/Brighton and Hove_pp_or_g_cmb
41,Portsmouth,Portsmouth_pp_or_g_cmb,../workflow_outputs/Portsmouth_pp_or_g_cmb
42,Southampton,Southampton_pp_or_g_cmb,../workflow_outputs/Southampton_pp_or_g_cmb
43,Isle of Wight,Isle of Wight_pp_or_g_cmb,../workflow_outputs/Isle of Wight_pp_or_g_cmb
44,County Durham,County Durham_pp_or_g_cmb,../workflow_outputs/County Durham_pp_or_g_cmb
45,Cheshire East,Cheshire East_pp_or_g_cmb,../workflow_outputs/Cheshire East_pp_or_g_cmb
46,Cheshire West and Chester,Cheshire West and Chester_pp_or_g_cmb,../workflow_outputs/Cheshire West and Chester_...
47,Shropshire,Shropshire_pp_or_g_cmb,../workflow_outputs/Shropshire_pp_or_g_cmb
48,Cornwall,Cornwall_pp_or_g_cmb,../workflow_outputs/Cornwall_pp_or_g_cmb
49,Isles of Scilly,Isles of Scilly_pp_or_g_cmb,../workflow_outputs/Isles of Scilly_pp_or_g_cmb
50,Wiltshire,Wiltshire_pp_or_g_cmb,../workflow_outputs/Wiltshire_pp_or_g_cmb
51,Bedford,Bedford_pp_or_g_cmb,../workflow_outputs/Bedford_pp_or_g_cmb
52,Central Bedfordshire,Central Bedfordshire_pp_or_g_cmb,../workflow_outputs/Central Bedfordshire_pp_or...
53,Northumberland,Northumberland_pp_or_g_cmb,../workflow_outputs/Northumberland_pp_or_g_cmb
54,"Bournemouth, Christchurch and Poole","Bournemouth, Christchurch and Poole_pp_or_g_cmb","../workflow_outputs/Bournemouth, Christchurch ..."
55,Cumberland,Cumberland_pp_or_g_cmb,../workflow_outputs/Cumberland_pp_or_g_cmb
56,Westmorland and Furness,Westmorland and Furness_pp_or_g_cmb,../workflow_outputs/Westmorland and Furness_pp...
57,North Yorkshire,North Yorkshire_pp_or_g_cmb,../workflow_outputs/North Yorkshire_pp_or_g_cmb
58,Leeds,Leeds_pp_or_g_cmb,../workflow_outputs/Leeds_pp_or_g_cmb

In [425]:
# for each folder_path in the area_df, find all parks in the area
# in the park_ids dataframe, find all parks with area_name in the area_df
# add the total number of parks in the area to the area_df
area_df["num_parks_total"] = area_df["area_name"].apply(lambda x: len(park_ids[park_ids["auth_name_e"] == x]))
area_df["expected_park_files"] = area_df["num_parks_total"].apply(lambda x: x * 2)

In [426]:
# then count the number of parks in the associated folder_path and add that to the area_df
def count_files_in_folder(folder_path):
    park_files = [f for f in os.listdir(folder_path) if f.endswith(".geojson")]
    return len(park_files)

area_df["completed_files"] = area_df["folder_path"].apply(count_files_in_folder)
area_df["completed_parks"] = area_df["completed_files"] / 2

In [427]:
area_df

,area_name,filename,folder_path,num_parks_total,expected_park_files,completed_files,completed_parks
0,Hartlepool,Hartlepool_pp_or_g_cmb,../workflow_outputs/Hartlepool_pp_or_g_cmb,38,76,76,38.0
1,Middlesbrough,Middlesbrough_pp_or_g_cmb,../workflow_outputs/Middlesbrough_pp_or_g_cmb,75,150,150,75.0
2,Redcar and Cleveland,Redcar and Cleveland_pp_or_g_cmb,../workflow_outputs/Redcar and Cleveland_pp_or...,75,150,150,75.0
3,Stockton-on-Tees,Stockton-on-Tees_pp_or_g_cmb,../workflow_outputs/Stockton-on-Tees_pp_or_g_cmb,393,786,786,393.0
4,Darlington,Darlington_pp_or_g_cmb,../workflow_outputs/Darlington_pp_or_g_cmb,65,130,130,65.0
5,Halton,Halton_pp_or_g_cmb,../workflow_outputs/Halton_pp_or_g_cmb,95,190,190,95.0
6,Warrington,Warrington_pp_or_g_cmb,../workflow_outputs/Warrington_pp_or_g_cmb,173,346,346,173.0
7,Blackburn with Darwen,Blackburn with Darwen_pp_or_g_cmb,../workflow_outputs/Blackburn with Darwen_pp_o...,101,202,202,101.0
8,Blackpool,Blackpool_pp_or_g_cmb,../workflow_outputs/Blackpool_pp_or_g_cmb,82,164,164,82.0
9,"Kingston upon Hull, City of","Kingston upon Hull, City of_pp_or_g_cmb","../workflow_outputs/Kingston upon Hull, City o...",155,310,310,155.0
10,East Riding of Yorkshire,East Riding of Yorkshire_pp_or_g_cmb,../workflow_outputs/East Riding of Yorkshire_p...,580,1160,1160,580.0
11,North East Lincolnshire,North East Lincolnshire_pp_or_g_cmb,../workflow_outputs/North East Lincolnshire_pp...,1377,2754,2754,1377.0
12,North Lincolnshire,North Lincolnshire_pp_or_g_cmb,../workflow_outputs/North Lincolnshire_pp_or_g...,6536,13072,13072,6536.0
13,York,York_pp_or_g_cmb,../workflow_outputs/York_pp_or_g_cmb,1505,3010,3010,1505.0
14,Derby,Derby_pp_or_g_cmb,../workflow_outputs/Derby_pp_or_g_cmb,174,348,348,174.0
15,Leicester,Leicester_pp_or_g_cmb,../workflow_outputs/Leicester_pp_or_g_cmb,197,394,394,197.0
16,Rutland,Rutland_pp_or_g_cmb,../workflow_outputs/Rutland_pp_or_g_cmb,96,192,192,96.0
17,Nottingham,Nottingham_pp_or_g_cmb,../workflow_outputs/Nottingham_pp_or_g_cmb,322,644,644,322.0
18,"Herefordshire, County of","Herefordshire, County of_pp_or_g_cmb","../workflow_outputs/Herefordshire, County of_p...",466,932,238,119.0
19,Telford and Wrekin,Telford and Wrekin_pp_or_g_cmb,../workflow_outputs/Telford and Wrekin_pp_or_g...,258,516,516,258.0
20,Stoke-on-Trent,Stoke-on-Trent_pp_or_g_cmb,../workflow_outputs/Stoke-on-Trent_pp_or_g_cmb,281,562,562,281.0
21,Bath and North East Somerset,Bath and North East Somerset_pp_or_g_cmb,../workflow_outputs/Bath and North East Somers...,170,340,340,170.0
22,"Bristol, City of","Bristol, City of_pp_or_g_cmb","../workflow_outputs/Bristol, City of_pp_or_g_cmb",425,850,850,425.0
23,North Somerset,North Somerset_pp_or_g_cmb,../workflow_outputs/North Somerset_pp_or_g_cmb,187,374,374,187.0
24,South Gloucestershire,South Gloucestershire_pp_or_g_cmb,../workflow_outputs/South Gloucestershire_pp_o...,510,1020,1020,510.0
25,Plymouth,Plymouth_pp_or_g_cmb,../workflow_outputs/Plymouth_pp_or_g_cmb,313,626,626,313.0
26,Torbay,Torbay_pp_or_g_cmb,../workflow_outputs/Torbay_pp_or_g_cmb,132,264,264,132.0
27,Swindon,Swindon_pp_or_g_cmb,../workflow_outputs/Swindon_pp_or_g_cmb,279,558,558,279.0
28,Peterborough,Peterborough_pp_or_g_cmb,../workflow_outputs/Peterborough_pp_or_g_cmb,426,852,852,426.0
29,Luton,Luton_pp_or_g_cmb,../workflow_outputs/Luton_pp_or_g_cmb,179,358,358,179.0
30,Southend-on-Sea,Southend-on-Sea_pp_or_g_cmb,../workflow_outputs/Southend-on-Sea_pp_or_g_cmb,71,142,142,71.0
31,Thurrock,Thurrock_pp_or_g_cmb,../workflow_outputs/Thurrock_pp_or_g_cmb,1703,3406,3406,1703.0
32,Medway,Medway_pp_or_g_cmb,../workflow_outputs/Medway_pp_or_g_cmb,2225,4450,4450,2225.0
33,Bracknell Forest,Bracknell Forest_pp_or_g_cmb,../workflow_outputs/Bracknell Forest_pp_or_g_cmb,129,258,258,129.0
34,West Berkshire,West Berkshire_pp_or_g_cmb,../workflow_outputs/West Berkshire_pp_or_g_cmb,175,350,350,175.0
35,Reading,Reading_pp_or_g_cmb,../workflow_outputs/Reading_pp_or_g_cmb,80,160,160,80.0
36,Slough,Slough_pp_or_g_cmb,../workflow_outputs/Slough_pp_or_g_cmb,298,596,596,298.0
37,Windsor and Maidenhead,Windsor and Maidenhead_pp_or_g_cmb,../workflow_outputs/Windsor and Maidenhead_pp_...,219,438,438,219.0
38,Wokingham,Wokingham_pp_or_g_cmb,../workflow_outputs/Wokingham_pp_or_g_cmb,155,310,310,155.0
39,Milton Keynes,Milton Keynes_pp_or_g_cmb,../workflow_outputs/Milton Keynes_pp_or_g_cmb,640,1280,1280,640.0
40,Brighton and Hove,Brighton and Hove_pp_or_g_cmb,../workflow_outputs/Brighton and Hove_pp_or_g_cmb,208,416,416,208.0
41,Portsmouth,Portsmouth_pp_or_g_cmb,../workflow_outputs/Portsmouth_pp_or_g_cmb,97,194,194,97.0
42,Southampton,Southampton_pp_or_g_cmb,../workflow_outputs/Southampton_pp_or_g_cmb,253,506,506,253.0
43,Isle of Wight,Isle of Wight_pp_or_g_cmb,../workflow_outputs/Isle of Wight_pp_or_g_cmb,438,876,876,438.0
44,County Durham,County Durham_pp_or_g_cmb,../workflow_outputs/County Durham_pp_or_g_cmb,1026,2052,2052,1026.0
45,Cheshire East,Cheshire East_pp_or_g_cmb,../workflow_outputs/Cheshire East_pp_or_g_cmb,1535,3070,3070,1535.0
46,Cheshire West and Chester,Cheshire West and Chester_pp_or_g_cmb,../workflow_outputs/Cheshire West and Chester_...,814,1628,1628,814.0
47,Shropshire,Shropshire_pp_or_g_cmb,../workflow_outputs/Shropshire_pp_or_g_cmb,1453,2906,2906,1453.0
48,Cornwall,Cornwall_pp_or_g_cmb,../workflow_outputs/Cornwall_pp_or_g_cmb,1351,2702,2702,1351.0
49,Isles of Scilly,Isles of Scilly_pp_or_g_cmb,../workflow_outputs/Isles of Scilly_pp_or_g_cmb,12,24,0,0.0
50,Wiltshire,Wiltshire_pp_or_g_cmb,../workflow_outputs/Wiltshire_pp_or_g_cmb,832,1664,1664,832.0
51,Bedford,Bedford_pp_or_g_cmb,../workflow_outputs/Bedford_pp_or_g_cmb,236,472,472,236.0
52,Central Bedfordshire,Central Bedfordshire_pp_or_g_cmb,../workflow_outputs/Central Bedfordshire_pp_or...,539,1078,598,299.0
53,Northumberland,Northumberland_pp_or_g_cmb,../workflow_outputs/Northumberland_pp_or_g_cmb,430,860,171,85.5
54,"Bournemouth, Christchurch and Poole","Bournemouth, Christchurch and Poole_pp_or_g_cmb","../workflow_outputs/Bournemouth, Christchurch ...",320,640,30,15.0
55,Cumberland,Cumberland_pp_or_g_cmb,../workflow_outputs/Cumberland_pp_or_g_cmb,1082,2164,101,50.5
56,Westmorland and Furness,Westmorland and Furness_pp_or_g_cmb,../workflow_outputs/Westmorland and Furness_pp...,849,1698,1698,849.0
57,North Yorkshire,North Yorkshire_pp_or_g_cmb,../workflow_outputs/North Yorkshire_pp_or_g_cmb,1049,2098,60,30.0
58,Leeds,Leeds_pp_or_g_cmb,../workflow_outputs/Leeds_pp_or_g_cmb,1058,2116,2116,1058.0

In [428]:
area_df["pct_complete"] = 100* area_df["completed_files"]/area_df["expected_park_files"]

In [429]:
area_df

,area_name,filename,folder_path,num_parks_total,expected_park_files,completed_files,completed_parks,pct_complete
0,Hartlepool,Hartlepool_pp_or_g_cmb,../workflow_outputs/Hartlepool_pp_or_g_cmb,38,76,76,38.0,100.000000
1,Middlesbrough,Middlesbrough_pp_or_g_cmb,../workflow_outputs/Middlesbrough_pp_or_g_cmb,75,150,150,75.0,100.000000
2,Redcar and Cleveland,Redcar and Cleveland_pp_or_g_cmb,../workflow_outputs/Redcar and Cleveland_pp_or...,75,150,150,75.0,100.000000
3,Stockton-on-Tees,Stockton-on-Tees_pp_or_g_cmb,../workflow_outputs/Stockton-on-Tees_pp_or_g_cmb,393,786,786,393.0,100.000000
4,Darlington,Darlington_pp_or_g_cmb,../workflow_outputs/Darlington_pp_or_g_cmb,65,130,130,65.0,100.000000
5,Halton,Halton_pp_or_g_cmb,../workflow_outputs/Halton_pp_or_g_cmb,95,190,190,95.0,100.000000
6,Warrington,Warrington_pp_or_g_cmb,../workflow_outputs/Warrington_pp_or_g_cmb,173,346,346,173.0,100.000000
7,Blackburn with Darwen,Blackburn with Darwen_pp_or_g_cmb,../workflow_outputs/Blackburn with Darwen_pp_o...,101,202,202,101.0,100.000000
8,Blackpool,Blackpool_pp_or_g_cmb,../workflow_outputs/Blackpool_pp_or_g_cmb,82,164,164,82.0,100.000000
9,"Kingston upon Hull, City of","Kingston upon Hull, City of_pp_or_g_cmb","../workflow_outputs/Kingston upon Hull, City o...",155,310,310,155.0,100.000000
10,East Riding of Yorkshire,East Riding of Yorkshire_pp_or_g_cmb,../workflow_outputs/East Riding of Yorkshire_p...,580,1160,1160,580.0,100.000000
11,North East Lincolnshire,North East Lincolnshire_pp_or_g_cmb,../workflow_outputs/North East Lincolnshire_pp...,1377,2754,2754,1377.0,100.000000
12,North Lincolnshire,North Lincolnshire_pp_or_g_cmb,../workflow_outputs/North Lincolnshire_pp_or_g...,6536,13072,13072,6536.0,100.000000
13,York,York_pp_or_g_cmb,../workflow_outputs/York_pp_or_g_cmb,1505,3010,3010,1505.0,100.000000
14,Derby,Derby_pp_or_g_cmb,../workflow_outputs/Derby_pp_or_g_cmb,174,348,348,174.0,100.000000
15,Leicester,Leicester_pp_or_g_cmb,../workflow_outputs/Leicester_pp_or_g_cmb,197,394,394,197.0,100.000000
16,Rutland,Rutland_pp_or_g_cmb,../workflow_outputs/Rutland_pp_or_g_cmb,96,192,192,96.0,100.000000
17,Nottingham,Nottingham_pp_or_g_cmb,../workflow_outputs/Nottingham_pp_or_g_cmb,322,644,644,322.0,100.000000
18,"Herefordshire, County of","Herefordshire, County of_pp_or_g_cmb","../workflow_outputs/Herefordshire, County of_p...",466,932,238,119.0,25.536481
19,Telford and Wrekin,Telford and Wrekin_pp_or_g_cmb,../workflow_outputs/Telford and Wrekin_pp_or_g...,258,516,516,258.0,100.000000
20,Stoke-on-Trent,Stoke-on-Trent_pp_or_g_cmb,../workflow_outputs/Stoke-on-Trent_pp_or_g_cmb,281,562,562,281.0,100.000000
21,Bath and North East Somerset,Bath and North East Somerset_pp_or_g_cmb,../workflow_outputs/Bath and North East Somers...,170,340,340,170.0,100.000000
22,"Bristol, City of","Bristol, City of_pp_or_g_cmb","../workflow_outputs/Bristol, City of_pp_or_g_cmb",425,850,850,425.0,100.000000
23,North Somerset,North Somerset_pp_or_g_cmb,../workflow_outputs/North Somerset_pp_or_g_cmb,187,374,374,187.0,100.000000
24,South Gloucestershire,South Gloucestershire_pp_or_g_cmb,../workflow_outputs/South Gloucestershire_pp_o...,510,1020,1020,510.0,100.000000
25,Plymouth,Plymouth_pp_or_g_cmb,../workflow_outputs/Plymouth_pp_or_g_cmb,313,626,626,313.0,100.000000
26,Torbay,Torbay_pp_or_g_cmb,../workflow_outputs/Torbay_pp_or_g_cmb,132,264,264,132.0,100.000000
27,Swindon,Swindon_pp_or_g_cmb,../workflow_outputs/Swindon_pp_or_g_cmb,279,558,558,279.0,100.000000
28,Peterborough,Peterborough_pp_or_g_cmb,../workflow_outputs/Peterborough_pp_or_g_cmb,426,852,852,426.0,100.000000
29,Luton,Luton_pp_or_g_cmb,../workflow_outputs/Luton_pp_or_g_cmb,179,358,358,179.0,100.000000
30,Southend-on-Sea,Southend-on-Sea_pp_or_g_cmb,../workflow_outputs/Southend-on-Sea_pp_or_g_cmb,71,142,142,71.0,100.000000
31,Thurrock,Thurrock_pp_or_g_cmb,../workflow_outputs/Thurrock_pp_or_g_cmb,1703,3406,3406,1703.0,100.000000
32,Medway,Medway_pp_or_g_cmb,../workflow_outputs/Medway_pp_or_g_cmb,2225,4450,4450,2225.0,100.000000
33,Bracknell Forest,Bracknell Forest_pp_or_g_cmb,../workflow_outputs/Bracknell Forest_pp_or_g_cmb,129,258,258,129.0,100.000000
34,West Berkshire,West Berkshire_pp_or_g_cmb,../workflow_outputs/West Berkshire_pp_or_g_cmb,175,350,350,175.0,100.000000
35,Reading,Reading_pp_or_g_cmb,../workflow_outputs/Reading_pp_or_g_cmb,80,160,160,80.0,100.000000
36,Slough,Slough_pp_or_g_cmb,../workflow_outputs/Slough_pp_or_g_cmb,298,596,596,298.0,100.000000
37,Windsor and Maidenhead,Windsor and Maidenhead_pp_or_g_cmb,../workflow_outputs/Windsor and Maidenhead_pp_...,219,438,438,219.0,100.000000
38,Wokingham,Wokingham_pp_or_g_cmb,../workflow_outputs/Wokingham_pp_or_g_cmb,155,310,310,155.0,100.000000
39,Milton Keynes,Milton Keynes_pp_or_g_cmb,../workflow_outputs/Milton Keynes_pp_or_g_cmb,640,1280,1280,640.0,100.000000
40,Brighton and Hove,Brighton and Hove_pp_or_g_cmb,../workflow_outputs/Brighton and Hove_pp_or_g_cmb,208,416,416,208.0,100.000000
41,Portsmouth,Portsmouth_pp_or_g_cmb,../workflow_outputs/Portsmouth_pp_or_g_cmb,97,194,194,97.0,100.000000
42,Southampton,Southampton_pp_or_g_cmb,../workflow_outputs/Southampton_pp_or_g_cmb,253,506,506,253.0,100.000000
43,Isle of Wight,Isle of Wight_pp_or_g_cmb,../workflow_outputs/Isle of Wight_pp_or_g_cmb,438,876,876,438.0,100.000000
44,County Durham,County Durham_pp_or_g_cmb,../workflow_outputs/County Durham_pp_or_g_cmb,1026,2052,2052,1026.0,100.000000
45,Cheshire East,Cheshire East_pp_or_g_cmb,../workflow_outputs/Cheshire East_pp_or_g_cmb,1535,3070,3070,1535.0,100.000000
46,Cheshire West and Chester,Cheshire West and Chester_pp_or_g_cmb,../workflow_outputs/Cheshire West and Chester_...,814,1628,1628,814.0,100.000000
47,Shropshire,Shropshire_pp_or_g_cmb,../workflow_outputs/Shropshire_pp_or_g_cmb,1453,2906,2906,1453.0,100.000000
48,Cornwall,Cornwall_pp_or_g_cmb,../workflow_outputs/Cornwall_pp_or_g_cmb,1351,2702,2702,1351.0,100.000000
49,Isles of Scilly,Isles of Scilly_pp_or_g_cmb,../workflow_outputs/Isles of Scilly_pp_or_g_cmb,12,24,0,0.0,0.000000
50,Wiltshire,Wiltshire_pp_or_g_cmb,../workflow_outputs/Wiltshire_pp_or_g_cmb,832,1664,1664,832.0,100.000000
51,Bedford,Bedford_pp_or_g_cmb,../workflow_outputs/Bedford_pp_or_g_cmb,236,472,472,236.0,100.000000
52,Central Bedfordshire,Central Bedfordshire_pp_or_g_cmb,../workflow_outputs/Central Bedfordshire_pp_or...,539,1078,598,299.0,55.473098
53,Northumberland,Northumberland_pp_or_g_cmb,../workflow_outputs/Northumberland_pp_or_g_cmb,430,860,171,85.5,19.883721
54,"Bournemouth, Christchurch and Poole","Bournemouth, Christchurch and Poole_pp_or_g_cmb","../workflow_outputs/Bournemouth, Christchurch ...",320,640,30,15.0,4.687500
55,Cumberland,Cumberland_pp_or_g_cmb,../workflow_outputs/Cumberland_pp_or_g_cmb,1082,2164,101,50.5,4.667283
56,Westmorland and Furness,Westmorland and Furness_pp_or_g_cmb,../workflow_outputs/Westmorland and Furness_pp...,849,1698,1698,849.0,100.000000
57,North Yorkshire,North Yorkshire_pp_or_g_cmb,../workflow_outputs/North Yorkshire_pp_or_g_cmb,1049,2098,60,30.0,2.859867
58,Leeds,Leeds_pp_or_g_cmb,../workflow_outputs/Leeds_pp_or_g_cmb,1058,2116,2116,1058.0,100.000000